<<<<<<< HEAD
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
=======
"use client";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });
>>>>>>> 40030bf5597fd217e26493d71f1d97ac46a5bf72

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
